package modelo;
// Generated 13-may-2015 9:59:48 by Hibernate Tools 4.3.1

/**
 * Examen generated by hbm2java
 */
public class Examen implements java.io.Serializable {

   private String id;
   private String nombre;
   private Curso curso;

   public Examen(String id, String nombre, Curso curso) {
      this.id = id;
      this.nombre = nombre;
      this.curso = curso;
   }

   public Examen() {
      this.id = "";
      this.nombre = "";
      this.curso = new Curso();
   }

   /**
    * @return the id
    */
   public String getId() {
      return id;
   }

   /**
    * @param id the id to set
    */
   public void setId(String id) {
      this.id = id;
   }

   /**
    * @return the nombre
    */
   public String getNombre() {
      return nombre;
   }

   /**
    * @param nombre the nombre to set
    */
   public void setNombre(String nombre) {
      this.nombre = nombre;
   }

   public Curso getCurso() {
      return curso;
   }

   public void setCurso(Curso curso) {
      this.curso = curso;
   }
}
